version: '3.8'
services:
    php-apache:
        container_name: vsnippet-deserialization-wakeup-30
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
